image: node:7.9.0 # change to match your node version

cache:
  paths:
    - node_modules/

before_script:
  - npm install

# test:
#   stage: test
#   script:
#     - CI=true npm test

pages:
  stage: deploy
  script:
    - CI=true npm run build
    - rm -rf public
    - mv build public
    - mv .well-known public/
    - mv robots.txt public/
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory
  only:
    - master # run on master branch
